from rdflib.namespace import Namespace

BF = Namespace("http://id.loc.gov/ontologies/bibframe/")
BFLC = Namespace("http://id.loc.gov/ontologies/bflc/")
CARRIER = Namespace("http://id.loc.gov/vocabulary/carriers/")
CM = Namespace("https://w3id.org/zpid/vocabs/carriermedia/")
CONTENT = Namespace("http://id.loc.gov/vocabulary/contentTypes/")
CONTENTTYPES = Namespace("http://id.loc.gov/vocabulary/contentTypes/")
GENRES = Namespace("https://w3id.org/zpid/vocabs/genres/")
INSTANCEBUNDLES = Namespace("https://w3id.org/zpid/resources/instancebundles/")
INSTANCES = Namespace("https://w3id.org/zpid/resources/instances/")
ISSUANCES = Namespace("https://w3id.org/zpid/vocabs/issuances/")
LANG = Namespace("http://id.loc.gov/vocabulary/iso639-2/")
LICENSES = Namespace("https://w3id.org/zpid/vocabs/licenses/")
LOCID = Namespace("http://id.loc.gov/vocabulary/identifiers/")
MADS = Namespace("http://www.loc.gov/mads/rdf/v1#")
MEDIA = Namespace("http://id.loc.gov/vocabulary/mediaTypes/")
METHODS = Namespace("https://w3id.org/zpid/vocabs/methods/")
PMT = Namespace("https://w3id.org/zpid/vocabs/mediacarriers/")
PMT = Namespace("https://w3id.org/zpid/vocabs/mediacarriers/")
PXC = Namespace("https://w3id.org/zpid/ontology/classes/")
PXP = Namespace("https://w3id.org/zpid/ontology/properties/")
RELATIONS = Namespace("https://w3id.org/zpid/vocabs/relations/")
ROLES = Namespace("https://w3id.org/zpid/vocabs/roles/")
SCHEMA = Namespace("https://schema.org/")
WORKS = Namespace("https://w3id.org/zpid/resources/works/")
