from rdflib.namespace import Namespace

BF = Namespace("http://id.loc.gov/ontologies/bibframe/")
BFLC = Namespace("http://id.loc.gov/ontologies/bflc/")
MADS = Namespace("http://www.loc.gov/mads/rdf/v1#")
SCHEMA = Namespace("https://schema.org/")
WORKS = Namespace("https://w3id.org/zpid/resources/works/")
INSTANCES = Namespace("https://w3id.org/zpid/resources/instances/")
INSTANCEBUNDLES = Namespace("https://w3id.org/zpid/resources/instancebundles/")
PXC = Namespace("https://w3id.org/zpid/ontology/classes/")
PXP = Namespace("https://w3id.org/zpid/ontology/properties/")
LANG = Namespace("http://id.loc.gov/vocabulary/iso639-2/")
LOCID = Namespace("http://id.loc.gov/vocabulary/identifiers/")
CONTENTTYPES = Namespace("http://id.loc.gov/vocabulary/contentTypes/")
ROLES = Namespace("https://w3id.org/zpid/vocabs/roles/")
ISSUANCES = Namespace("https://w3id.org/zpid/vocabs/issuances/")
RELATIONS = Namespace("https://w3id.org/zpid/vocabs/relations/")
GENRES = Namespace("https://w3id.org/zpid/vocabs/genres/")
PMT = Namespace("https://w3id.org/zpid/vocabs/mediacarriers/")
LICENSES = Namespace("https://w3id.org/zpid/vocabs/licenses/")
