# list all works whose InstanceBundle have an issuance of JournalArticle, but not a genreForm of ResearchPaper

PREFIX works: <https://w3id.org/zpid/resources/works/>
PREFIX roles: <https://w3id.org/zpid/vocabs/roles/>
PREFIX pxc: <https://w3id.org/zpid/ontology/classes/>
PREFIX pxp: <https://w3id.org/zpid/ontology/properties/>
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX bflc: <http://id.loc.gov/ontologies/bflc/>
PREFIX locid: <http://id.loc.gov/vocabulary/identifiers/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mads: <http://www.loc.gov/mads/rdf/v1#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?work ?dfk ?genre ?issuance
WHERE {
  ?work a pxc:MainWork.
  ?work pxp:hasInstanceBundle ?instanceBundle .
  ?instanceBundle bf:identifiedBy ?dfk_uri .
  ?dfk_uri a pxc:DFK; rdf:value ?dfk .
  ?instanceBundle pxp:issuanceType ?issuance .
  ?work bf:genreForm ?genre .
  FILTER (?issuance = <https://w3id.org/zpid/vocabs/issuances/JournalArticle>)
  FILTER (?genre != <https://w3id.org/zpid/vocabs/genres/ResearchPaper>)
}

# run with:
# arq --data ttl-data/bibframe_records.ttl --query testing/genreForm/nonresearch_journalarticles.rq  --results=TSV > testing/genreForm/nonresearch_journalarticles.tsv