academic_titles = [
    {"number": 1, "name": "Prof. Dr."},
    {"number": 2, "name": "Jun. Prof. Dr."},
    {"number": 3, "name": "Dr."},
    {"number": 4, "name": "Dipl.-Psych."},
    {"number": 5, "name": "PD Dr."},
    {"number": 6, "name": "M.A."},
    {"number": 7, "name": "apl. Prof. Dr."},
    {"number": 8, "name": "Prof. em. Dr."},
    {"number": 9, "name": "Prof."},
    {"number": 10, "name": "Prof. Dr. rer. nat. habil."},
    {"number": 11, "name": "Prof. Dr. Dr. h.c."},
    {"number": 12, "name": "Prof. Dr. phil."},
    {"number": 13, "name": "Prof. em."},
    {"number": 14, "name": "lic. Phil."},
    {"number": 15, "name": "M. Sc."},
    {"number": 16, "name": "B. Sc."},
    {"number": 17, "name": "Mag."},
    {"number": 18, "name": "Mag. Dr."},
    {"number": 19, "name": "Prof. Mag. Dr."},
    {"number": 20, "name": "Dr. des."},
    {"number": 21, "name": "Ao.Univ.-Prof. Mag. Dr."},
    {"number": 22, "name": "Dr. phil."},
    {"number": 23, "name": "Prof. (FH) Univ. Doz. Dr."},
    {"number": 24, "name": "Ao.Univ.-Prof. Dr."},
    {"number": 25, "name": "Dr. phil., em. o. Univ.-Prof."},
    {"number": 26, "name": "Mag.rer.nat. Dr.phil."},
    {"number": 87, "name": "AkadR Dr."},
    {"number": 54, "name": "Prof. Dr. rer. nat."},
    {"number": 32, "name": "Prof. Dr. med."},
    {"number": 34, "name": "PD Dr. Dr."},
    {"number": 35, "name": "Dr. Dipl.-Psych."},
    {"number": 36, "name": "Oberassistent Prof. Dr."},
    {"number": 37, "name": "Prof. Dr. Dr."},
    {"number": 38, "name": "Prof Dr. med. Dr. phil."},
    {"number": 39, "name": "Univ.-Prof. Dr."},
    {"number": 40, "name": "Prof. Dr. Dr. h.c. mult."},
    {"number": 41, "name": "Ass. Prof. Dr."},
    {"number": 42, "name": "Dr. rer. nat."},
    {"number": 55, "name": "Dr. med. Dr. phil Dipl.-Psych"},
    {"number": 44, "name": "Prof. Dr. rer. soc. Dipl. Psyc"},
    {"number": 45, "name": "Dr. sc. hum."},
    {"number": 46, "name": "Ph.D."},
    {"number": 47, "name": "Dr. med."},
    {"number": 48, "name": "Prof. Dr. med. Dr. med. h.c."},
    {"number": 49, "name": "Dr. med Dr. rer.nat."},
    {"number": 50, "name": "Prof. i. K. Dr."},
    {"number": 51, "name": "Dr. med. Dipl.-Psych."},
    {"number": 52, "name": "Dr. rer. med. Dipl.-Psych."},
    {"number": 53, "name": "Prof. em. Dr. Dr.h.c.mult."},
    {"number": 56, "name": "apl. Prof. Dr. phil."},
    {"number": 57, "name": "Prof. i.R. Dr. phil."},
    {"number": 58, "name": "PD"},
    {"number": 59, "name": "Dr. phil.,  Dipl.-Psych., MA"},
    {"number": 60, "name": "Prof. Dr. i.R."},
    {"number": 61, "name": "Dipl.-Psych. Dr."},
    {"number": 62, "name": "Mag.rer.nat."},
    {"number": 63, "name": "Dr. rer. medic."},
    {"number": 64, "name": "PD Dr. sc. hum."},
    {"number": 65, "name": "Prof. Dr. phil.Dr.med"},
    {"number": 67, "name": "Dipl.-Sozialwiss."},
    {"number": 68, "name": "Dr. phil. nat."},
    {"number": 69, "name": "PD Dr. habil."},
    {"number": 70, "name": "Mag.rer.nat. Dr.rer.nat."},
    {"number": 71, "name": "Dr. phil.,  Dipl.-Psych."},
    {"number": 72, "name": "Dr. rer. nat. Dipl. Psych."},
    {"number": 73, "name": "Prof. Dr. em."},
    {"number": 74, "name": "PD Dr. rer. nat., phil."},
    {"number": 75, "name": "Dr. rer."},
    {"number": 76, "name": "PD Dr. phil."},
    {"number": 78, "name": "Prof. Dr. med. Dr. phil."},
    {"number": 92, "name": "Jun.-Prof. Dr."},
    {"number": 83, "name": "Prof. i.R."},
    {"number": 91, "name": "Mag. Dr. Dr."},
    {"number": 89, "name": "Prof. Dr. phil. habil."},
    {"number": 90, "name": "Dr.rer.nat.; Dipl.- Psych."},
    {"number": 93, "name": "a.Univ.-Prof. Dr."},
    {"number": 94, "name": "Prof. Dr. habil."},
    {"number": 95, "name": "Ao.Univ.-Prof. i.R. Dr."},
    {"number": 96, "name": "Dr. Dr."},
    {"number": 98, "name": "JProf. Dr."},
    {"number": 99, "name": "Dr. rer. nat.., Dr. rer. medic"},
    {"number": 100, "name": "Dr. rer. nat., Dr. rer. medic"},
    {"number": 101, "name": "Dr. rer. nat., Dr. rer. medic."},
    {"number": 102, "name": "Prof. Dr. hc."},
    {"number": 103, "name": "Prof. Dr. sc. hum."},
    {"number": 104, "name": "Ass.-Prof. Mag. Dr."},
    {"number": 105, "name": "Univ.-Prof. Dr. phil. habil."},
    {"number": 106, "name": "Prof. (em.) Dr."},
    {"number": 107, "name": "Dr. med. habil."},
    {"number": 108, "name": "Prof. i.R. Dr."},
    {"number": 109, "name": "Prof"},
    {"number": 110, "name": "Dr. h.c."},
    {"number": 111, "name": "Dr. phil. h.c."},
    {"number": 112, "name": "Dr. med. hon"},
    {"number": 113, "name": "M.D., Dr. med. hon"},
    {"number": 114, "name": "Pro"},
    {"number": 115, "name": "D"},
    {"number": 116, "name": "Dr"},
    {"number": 117, "name": "Priv.-Doz. Dr.phil."},
    {"number": 118, "name": "Univ.-Doz. Dr."},
    {"number": 119, "name": "Univ-Prof. Dr. rer. oec."},
    {"number": 120, "name": "Prof. Dr.med. Dr.phil."},
    {"number": 121, "name": "PD, Dr.rer.soc."},
    {"number": 122, "name": "Univ.-Prof. Dr. rer. nat."},
    {"number": 123, "name": "Pr"},
    {"number": 124, "name": "Di"},
    {"number": 125, "name": "Univ.-Prof. em., Dr. rer.nat."},
    {"number": 126, "name": "Dipl"},
    {"number": 127, "name": "Prof. Dr. phil. Dipl.-Psych."},
    {"number": 128, "name": "Dip. Oec."},
    {"number": 129, "name": "Prof. Dr. med. Dr. rer. nat."},
    {"number": 130, "name": "Jun."},
    {"number": 131, "name": "Prof. (apl.) Dr."},
    {"number": 132, "name": "D. Phil."},
    {"number": 133, "name": "Prof. em. Dr. phil."},
    {"number": 134, "name": "Dr. sc."},
    {"number": 135, "name": "Ph.D., Dipl.-Psych."},
    {"number": 136, "name": "Prof. (em.) Dr. phil."},
    {"number": 137, "name": "PhD"},
    {"number": 138, "name": "PD Dr. rer. nat.."},
    {"number": 139, "name": "Dr.phil."},
    {"number": 140, "name": "Dr.p"},
    {"number": 141, "name": "Priv.-Doz."},
    {"number": 142, "name": "Priv.-Doz. Dr. rer. medic."},
    {"number": 143, "name": "PD Dr. rer. nat."},
    {"number": 144, "name": "Priv.-Doz./ Dr. habil rer. nat"},
    {"number": 145, "name": "Priv.-Doz./ Dr."},
    {"number": 146, "name": "Priv.-Doz. Dr."},
    {"number": 147, "name": "Prof. em Dr."},
    {"number": 148, "name": "Prof. Dr. Dr. em."},
    {"number": 149, "name": "M.Sc. M.Sc."},
    {"number": 150, "name": "Prof. PhD"},
    {"number": 151, "name": "Diplom-Psychologe, M. Sc."},
    {"number": 152, "name": "Prof. Dr. (habil.)"},
    {"number": 153, "name": "Jun. Prof. Dr. phil"},
    {"number": 154, "name": "Ao.Univ.-Prof. (i.R.) Dr."},
    {"number": 155, "name": "Prof. Dr. rer. nat., phil."},
    {"number": 156, "name": "Prof. Dr. phil.,  Dipl.-Psych."},
    {"number": 157, "name": "Prof. Dr. Dipl.-Psych."},
]

research_subjects = [
    {"number": 1, "name": "A&O Psychologie"},
    {"number": 2, "name": "Diagnostik"},
    {"number": 3, "name": "Klinische Psychologie"},
    {"number": 4, "name": "Methodenlehre/Statistik"},
    {"number": 5, "name": "Bio- und Neuropsychologie"},
    {"number": 6, "name": "Differentielle Psychologie"},
    {"number": 7, "name": "Entwicklungspsychologie"},
    {"number": 8, "name": "Allgemeine Psychologie"},
    {"number": 9, "name": "Pädagogische Psychologie"},
    {"number": 10, "name": "Sozialpsychologie"},
    {"number": 11, "name": "Sportpsychologie"},
    {"number": 12, "name": "Militärpsychologie"},
    {"number": 13, "name": "Marktpsychologie"},
    {"number": 14, "name": "Umweltpsychologie"},
    {"number": 15, "name": "Rechtspsychologie"},
    {"number": 16, "name": "Gesundheitspsychologie"},
    {"number": 17, "name": "Psychoanalyse"},
    {"number": 18, "name": "Verkehrspsychologie"},
    {"number": 19, "name": "Ethnopsychologie"},
    {"number": 20, "name": "Kulturpsychologie"},
    {"number": 24, "name": "Geschichte der Psychologie"},
    {"number": 25, "name": "Gesellschaftliche Fragen"},
    {"number": 26, "name": "Psychologische Beratung"},
    {"number": 27, "name": "Medienpsychologie"},
    {"number": 28, "name": "Persönlichkeitspsychologie"},
    {"number": 29, "name": "Wirtschaftspsychologie"},
    {"number": 30, "name": "E-Learning"},
    {"number": 31, "name": "Medizinische Psychologie"},
]

# a set of different strings that may be used in the data to represent the same university
college_lookup = [
    {
        "name": "Universität Trier",
        "ror": "https://ror.org/02778hg05",
        "synonyms": ["Trier"],
    },
    {
        "name": "Universität des Saarlandes",
        "ror": "https://ror.org/01jdpyv68",
        "synonyms": ["Saarland", "Saarbrücken"],
    },
    {
        "name": "Julius-Maximilians-Universität Würzburg",
        "ror": "https://ror.org/00fbnyb24",
        "synonyms": ["Würzburg"],
    },
    {
        "name": "Philipps-Universität Marburg",
        "ror": "https://ror.org/01rdrb571",
        "synonyms": ["Marburg"],
    },
    {
        "name": "Eberhard Karls Universität Tübingen",
        "ror": "https://ror.org/03a1kwz48",
        "synonyms": ["Tübingen"],
    },
    {
        "name": "Universität Münster",
        "ror": "https://ror.org/00pd74e08",
        "synonyms": ["Münster"],
    },
    {
        "name": "Christian-Albrechts-Universität zu Kiel",
        "ror": "https://ror.org/04v76ef78",
        "synonyms": ["Kiel"],
    },
    {
        "name": "Friedrich-Schiller-Universität Jena",
        "ror": "https://ror.org/05qpz1x62",
        "synonyms": ["Jena"],
    },
    {
        "name": "Freie Universität Berlin",
        "ror": "https://ror.org/046ak2485",
        "synonyms": [
            "Freie Universität Berlin",
            "FU Berlin",
            "Berlin FU",
            "Free University Berlin",
            "Freien Universität Berlin",
        ],
    },
    {
        "name": "Technische Universität Berlin",
        "ror": "https://ror.org/03v4gjf40",
        "synonyms": ["Technische Universität Berlin", "TU Berlin", "Berlin TU"],
    },
    {
        "name": "Humboldt-Universität zu Berlin",
        "ror": "https://ror.org/01hcx6992",
        "synonyms": [
            "Humboldt-Universit",
            "Humboldt Universit",
            "HU Berlin",
            "Berlin HU",
        ],
    },
    {
        "name": "Universität Konstanz",
        "ror": "https://ror.org/0546hnb39",
        "synonyms": ["Konstanz"],
    },
    {
        "name": "Ruhr-Universität Bochum",
        "ror": "https://ror.org/04tsk2644",
        "synonyms": ["Bochum"],
    },
    {
        "name": "Universität Mannheim",
        "ror": "https://ror.org/031bsb921",
        "synonyms": ["Mannheim"],
    },
    {
        "name": "Rheinische Friedrich-Wilhelms-Universität Bonn",
        "ror": "https://ror.org/041nas322",
        "synonyms": ["Bonn"],
    },
    {
        "name": "Technische Universität Dresden",
        "ror": "https://ror.org/042aqky30",
        "synonyms": ["Dresden"],
    },
    {
        "name": "Johannes Gutenberg-Universität Mainz",
        "ror": "https://ror.org/023b0x485",
        "synonyms": ["Mainz"],
    },
    {
        "name": "Goethe-Universität Frankfurt am Main",
        "ror": "https://ror.org/04cvxnb49",
        "synonyms": ["Frankfurt"],
    },
    {
        "name": "Universität Bielefeld",
        "ror": "https://ror.org/02hpadn98",
        "synonyms": ["Bielefeld"],
    },
    {
        "name": "Georg-August-Universität Göttingen",
        "ror": "https://ror.org/01y9bpm73",
        "synonyms": ["Göttingen"],
    },
    {
        "name": "Universität Leipzig",
        "ror": "https://ror.org/03s7gtk40",
        "synonyms": ["Leipzig"],
    },
    {
        "name": "Justus-Liebig-Universität Gießen",
        "ror": "https://ror.org/033eqas34",
        "synonyms": ["Gießen", "Giessen"],
    },
    {
        "name": "Technische Universität Braunschweig",
        "ror": "https://ror.org/010nsgg66",
        "synonyms": ["Braunschweig"],
    },
    {
        "name": "Paris Lodron Universität Salzburg",
        "ror": "https://ror.org/05gs8cd61",
        "synonyms": ["Salzburg"],
    },
    {
        "name": "Universität Regensburg",
        "ror": "https://ror.org/01eezs655",
        "synonyms": ["Regensburg"],
    },
    {
        "name": "Heinrich-Heine-Universität Düsseldorf",
        "ror": "https://ror.org/024z2rq82",
        "synonyms": ["Düsseldorf"],
    },
    {
        "name": "Otto-Friedrich-Universität Bamberg",
        "ror": "https://ror.org/01c1w6d29",
        "synonyms": ["Bamberg"],
    },
    {
        "name": "Universität Greifswald",
        "ror": "https://ror.org/00r1edq15",
        "synonyms": ["Greifswald"],
    },
    {
        "name": "Universität Bern",
        "ror": "https://ror.org/02k7v4d05",
        "synonyms": ["Bern"],
    },
    {
        "name": "Technische Universität Darmstadt",
        "ror": "https://ror.org/05n911h24",
        "synonyms": ["Darmstadt"],
    },
    {
        "name": "Universität Osnabrück",
        "ror": "https://ror.org/04qmmjx98",
        "synonyms": ["Osnabrück"],
    },
    {
        "name": "Carl von Ossietzky Universität Oldenburg",
        "ror": "https://ror.org/033n9gh91",
        "synonyms": ["Oldenburg"],
    },
    {
        "name": "Technische Universität Chemnitz",
        "ror": "https://ror.org/00a208s56",
        "synonyms": ["Chemnitz"],
    },
    {
        "name": "Ludwig-Maximilians-Universität München (LMU)",
        "ror": "https://ror.org/02y2zjx62",
        "synonyms": [
            " München",
            "Universität München",
            "Uni München",
            "LMU München",
            "LMU-München",
            "Ludwig-Maximilians",
        ],
    },
    {
        "name": "Rheinisch-Westfälische Technische Hochschule Aachen",
        "ror": "https://ror.org/04xfq0f34",
        "synonyms": ["Aachen"],
    },
    {
        "name": "Universität Innsbruck",
        "ror": "https://ror.org/054pv6659",
        "synonyms": ["Innsbruck"],
    },
    {
        "name": "Otto-von-Guericke-Universität Magdeburg",
        "ror": "https://ror.org/00ggpsq73",
        "synonyms": ["Magdeburg"],
    },
    {
        "name": "Martin-Luther-Universität Halle-Wittenberg",
        "ror": "https://ror.org/05gqaka33",
        "synonyms": ["Halle"],
    },
    {
        "name": "University of Management and Communication Potsdam",
        "synonyms": ["UMC Potsdam"],
    },
    {
        "name": "Universität Potsdam",
        "ror": "https://ror.org/03bnmw459",
        "synonyms": ["Potsdam"],
    },
    {
        "name": "Bergische Universität Wuppertal",
        "ror": "https://ror.org/00613ak93",
        "synonyms": ["Wuppertal"],
    },
    # {
    #     "name": "Universität Duisburg-Essen",
    #     "ror": "https://ror.org/04mz5ra38",
    #     "synonyms": ["Duisburg", "Essen"],
    # },
    {
        "name": "Universität Kassel",
        "ror": "https://ror.org/04zc7p361",
        "synonyms": ["Kassel"],
    },
    {
        "name": "Universität Augsburg",
        "ror": "https://ror.org/03p14d497",
        "synonyms": ["Augsburg"],
    },
    {
        "name": "Universität Ulm",
        "ror": "https://ror.org/032000t02",
        "synonyms": ["Ulm"],
    },
    {
        "name": "Katholische Universität Eichstätt-Ingolstadt",
        "ror": "https://ror.org/00mx91s63",
        "synonyms": ["Eichstätt"],
    },
    {
        "name": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
        "ror": "https://ror.org/00f7hpc57",
        "synonyms": ["Erlangen"],
    },
    {
        "name": "Stiftung Universität Hildesheim",
        "ror": "https://ror.org/02f9det96",
        "synonyms": ["Hildesheim"],
    },
    {
        "name": "Leuphana Universität Lüneburg",
        "ror": "https://ror.org/02w2y2t16",
        "synonyms": ["Lüneburg"],
    },
    {
        "name": "Universität Witten/Herdecke",
        "ror": "https://ror.org/00yq55g44",
        "synonyms": ["Herdecke"],
    },
    {
        "name": "Universität Hohenheim",
        "ror": "https://ror.org/00b1c9541",
        "synonyms": ["Hohenheim"],
    },
    {
        "name": "Technische Universität Dortmund",
        "ror": "https://ror.org/01k97gp34",
        "synonyms": ["Dortmund"],
    },
    {
        "name": "Eidgenössische Technische Hochschule Zürich",
        "ror": "https://ror.org/05a28rw58",
        "synonyms": ["ETH Zürich"],
    },
    {
        "name": "Universität Zürich",
        "ror": "https://ror.org/02crff812",
        "synonyms": [
            ", Zürich",
            "Uni Zürich",
            "Universität Zürich",
            "University of Zurich",
        ],
    },
    {
        "name": "FernUniversität in Hagen",
        "ror": "https://ror.org/04tkkr536",
        "synonyms": ["Hagen"],
    },
    {
        "name": "Universität Passau",
        "ror": "https://ror.org/05ydjnb78",
        "synonyms": ["Passau"],
    },
    {
        "name": "Universität Vechta",
        "ror": "https://ror.org/045y6d111",
        "synonyms": ["Vechta"],
    },
    {
        "name": "Universität Siegen",
        "ror": "https://ror.org/02azyry73",
        "synonyms": ["Siegen"],
    },
    {
        "name": "Universität Rostock",
        "ror": "https://ror.org/03zdwsf69",
        "synonyms": ["Rostock"],
    },
    {
        "name": "Universität Bayreuth",
        "ror": "https://ror.org/0234wmv40",
        "synonyms": ["Bayreuth"],
    },
    {
        "name": "Universität zu Köln",
        "ror": "https://ror.org/00rcxh774",
        "synonyms": [
            "Uni Köln",
            "Universität Köln",
            "Erstberufung Köln",
            "Promotion Köln",
            ", Köln",
            "Univ. zu Köln",
            "Universität zu Köln",
        ],
    },
    {
        "name": "Constructor University Bremen",
        "ror": "https://ror.org/02yrs2n53",
        "synonyms": ["Jacobs Universität Bremen", "Jacobs University Bremen"],
    },
    {
        "name": "Universität Bremen",
        "ror": "https://ror.org/04ers2y35",
        "synonyms": [", Bremen", "Universität Bremen", "Uni Bremen"],
    },
    {
        "name": "Technische Universität München",
        "ror": "https://ror.org/02kkvpp62",
        "synonyms": ["TU München"],
    },
    {
        "name": "Albert-Ludwigs-Universität Freiburg",
        "ror": "https://ror.org/0245cg223",
        "synonyms": [" Freiburg", "Uni Freiburg", "Universität Freiburg"],
    },
    {
        "name": "Gottfried Wilhelm Leibniz Universität Hannover",
        "ror": "https://ror.org/0304hq317",
        "synonyms": [", Hannover", "Uni Hannover", "Universität Hannover"],
    },
    {
        "name": "Universität Paderborn",
        "ror": "https://ror.org/058kzsd48",
        "synonyms": [", Paderborn", "Uni Paderborn", "Universität Paderborn"],
    },
    {
        "name": "Universität Hamburg",
        "ror": "https://ror.org/00g30e956",
        "synonyms": [", Hamburg", "Uni Hamburg", "Universität Hamburg"],
    },
    {
        "name": "Ruprecht-Karls-Universität Heidelberg",
        "ror": "https://ror.org/038t36y30",
        "synonyms": [
            " Heidelberg",
            " heidelberg",
            "Uni Heidelberg",
            "Universität Heidelberg",
        ],
    },
    {
        "name": "Universität Wien",
        "ror": "https://ror.org/03prydq77",
        "synonyms": [", Wien", "Universität Wien", "Uni Wien"],
    },
    {
        "name": "Universität Graz",
        "ror": "https://ror.org/01faaaf77",
        "synonyms": [", Graz", "Uni Graz", "Universität Graz"],
    },
    {
        "name": "Universität Klagenfurt",
        "ror": "https://ror.org/05q9m0937",
        "synonyms": [", Klagenfurt", "Uni Klagenfurt", "Universität Klagenfurt"],
    },
    {
        "name": "Universität Fribourg",
        "ror": "https://ror.org/022fs9h90",
        "synonyms": [", Fribourg", "Universität Fribourg"],
    },
    {
        "name": "Universität Koblenz-Landau",
        "ror": "https://ror.org/01j9f6752",
        "synonyms": ["Koblenz", "Landau"],
    },
    {
        "name": "Universität Basel",
        "ror": "https://ror.org/02s6k3f65",
        "synonyms": [", Basel", "Uni Basel", "Universität Basel"],
    },
    # {"name": "", "ror": "", "synonyms": [""]},
]


degree_lookup = [
    {
        "name": "bachelorLevel",
        "synonyms": [
            "Bachelor",
            "Vordiplom",
            "B.Ed.",
            "BA",
            "B.A.",
            "B.Sc.",
            "BSc",
            "B.A.",
        ],
    },
    {
        "name": "masterLevel",
        "synonyms": [
            "Diplom",
            "Diolom",
            "diplom",
            "Dipl.",
            "Master",
            "Lizenziat",
            "Lizentiat",
            "Licentiat",
            "Lic.",
            "Magist",
            "Mag.",
            "M.A.",
            "MA",
            "MSc",
            "M.Sc.",
        ],
    },
    {
        "name": "habilitationLevel",
        "synonyms": [
            "Habilitation",
            "Habitilation",
            "Habilitand",
            "Habilitaion",
            "Habilation",
            "Habiliation",
            "Habililtation",
            "Habillitation",
            "Venia",
            "venia",
            "Professur",
            "Professor",
            "Pofessor",
            "Erstberufung",
            "Erstruf",
            "Ruf",
            "professorship",
            "Univ.-Prof.",
        ],
    },
    {
        "name": "doctoralLevel",
        "synonyms": [
            "Promotion",
            "Promotin",
            "Promoion",
            "Promition",
            "Dissertation",
            "Doctor",
            "Doktor",
            "Dr.",
            "Ph.",
            "PhD",
            "Phd",
        ],
    },
    {
        "name": "therapistApprobation",
        "synonyms": ["Approbation", "therapeut", "Anerkennung"],
    },
]
